spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 2s
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}


jwt:
  secret: ${JWT_SECRET}

auth-service:
  base-url: ${AUTH_BASE_URL}
  client-id: ${AUTH_CLIENT_ID}
  client-secret: ${AUTH_CLIENT_SECRET}