spring:
  application:
    name: urlShortner

  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener_db
    username: springstudent
    password: harsh

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      database: 1

server:
  port: 8081

jwt:
  secret: 2qaf7BS4drDUvKsjPDR7flYFSkR0jBW48O8/IusbytBVqZ4KAxPrJAL0ZUc9+rXtDsWLY0vIJ+ZBSS8IpuDD0w==

auth-service:
  base-url: ${AUTH_SERVICE_URL:http://localhost:8080}
  client-id: cd8cd833-750c-4179-8668-7de0f49682db
  client-secret: d8mxS9YYC5buDvbNqWaG9Tw6abwrBflY6dfjL3rLtAc