spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  application:
    name: urlShortner

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  datasource:
    hikari:
      initialization-fail-timeout: -1
      minimum-idle: 0
      idle-timeout: 30000
      max-lifetime: 600000
      keepalive-time: 0

  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  port: ${SERVER_PORT:8081}
  shutdown: graceful

logging:
  level:
    root: INFO
    bdj.hkb.urlShortner: INFO